export const Globals = {
  array_concursantes_test: [
    "kamila Villablanca",
    "Daniela Salvador Caballero",
    "LeoGarcia01",
    "Gaspak",
    "IShow Speed",
    "Mauro Toranzo",
    "Gerardo Garcia Hernandez",
    "Ibai llanos",
    "Pierre Zurita Ramirez",
    "samp play",
    "Eduardo Joel Paucarpura Sanchez",
    "Anthony Espino",
    "Jordan Team",
    "Gerardo Garcia Hernandez",
    "Rivaldo Smith",
    "Oxmar Yamith",
    "Rigoberto Uran",
    "Oxmar Yamith",
    "Gerardo Garcia Hernandez",
    "TheComicalCanadian",
  ],
  array_concursantes: [],
  angle: null,
  angleInit: null,
  angleWaiting: null,
};
